### ISSUE TITLE
error when turning on executables

### ISSUE THREAD

**Issue by weiliu620** [GeertLitjens/ASAP#5]
When I turn on "BUILD_DIAG_PATHOLOGY_EXECUTABL", I got the following error: 

[ 20%] Built target core
[ 50%] Built target multiresolutionimageinterface
[ 76%] Built target annotation
[ 82%] Built target _multiresolutionimageinterface
Linking CXX executable MultiResImageConverter
[ 85%] Built target MultiResImageConverter
Scanning dependencies of target WSIConnectedComponents
[ 88%] Building CXX object executables/WSIConnectedComponents/CMakeFiles/WSIConnectedComponents.dir/WSIConnectedComponents.cpp.o
Linking CXX executable WSIConnectedComponents
/usr/bin/ld: cannot find -lwholeslidefilters
collect2: error: ld returned 1 exit status
make[2]: *** [executables/WSIConnectedComponents/WSIConnectedComponents] Error 1
make[1]: *** [executables/WSIConnectedComponents/CMakeFiles/WSIConnectedComponents.dir/all] Error 2
make: *** [all] Error 2
====================
I use Ubuntu 14.04 LTS 64 bit.

**Comment by weiliu620** [comment]
Update: I can open the image processing options in cmake (which need to add -std=c++11 in compiler flag) and it looks it builds wholeslidefilters library, and can solve this dependency. 

Then I got another error: 
Linking CXX executable MultiResImageConverter
../../core/libcore.so: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'

==========================
It seems my boost library is not compatible or too old for this package.

**Comment by weiliu620** [comment]
Update again: after upgrading my boost to 1.60, I'm able to build the 'executable', 'image processing' and 'workstation'. 

Now I"m able to load images into the 'workstation' viewer. Great tools!

I hope I can find some documentation.
